### ISSUE TITLE
Filtering and merging a reduced scope based on name or type

### ISSUE THREAD

**Issue by etraisnel2** [eclipse/org.eclipse.emf.diffmerge.core#254]
Textual Filter

In DiffMerge dialogs, provide a reg exp field in the left tree to enable the capability to filter elements based on their name
This field should not only filter what items are displayed in the tree, but instead recompute the comparison so that non-matching elements are excluded (EElementPresence only)

1/ Adapt the ComparisonViewer to give the capability to filter the tree (See FilteredTree)

2/ Adapt the filtering process, so that it acts on the comparison itself (as difference categories do) and not only on what is displayed in the tree

3/ Ensure that the filter is only enabled when there is text in the text area and that "enter" key was pressed (do not allow dynamic filtering while the user is typing, this would induce performance issues

3b/ (TODO) for diffmerge dialogs, pressing the enter button closes the dialog instead (since it clicks the OK buttton), change that to have the same behaviour as in a diffmerge editor
Impacted dialogs :
- REC/RPL (Update REC / Update connections )
- any Transition dialog 

--------------------------------------------------------------------------------------------------------------------------------------------
Graphical changes  :

Update icons/menus/tootip labels, in order to replace "Difference Categories" with "Filters and Customization" to reflect Capella Project Explorer' filters

No JUnit to provide
![image](https://user-images.githubusercontent.com/109157813/202439900-b125bb9d-71e7-436d-b78a-7e5ec3771e35.png)
![image](https://user-images.githubusercontent.com/109157813/202439983-e7f3f314-120f-4d2c-b358-c29fd4ee211d.png)
![image](https://user-images.githubusercontent.com/109157813/202440062-b85b5b0b-3df3-4b6d-a0a3-991a581d49b1.png)

--------------------------------------------------------------------------------------------------------------------------------------------
Capella Project Explorer filters -> category filters on diffmerge in Capella context
 (see https://github.com/eclipse/capella/issues/2511)

--------------------------------------------------------------------------------------------------------------------------------------------
Git decorators in oriented comparison

For oriented merges (left to right and right to left) use git decorators (and use same colors as previously)
1) Adapt the GitDiffLike label provider so that it uses the same color schema as the previous provider
2) Adapt the viewer to ensures that the label provider is properly changed when changing the comparison direction 
3) Use the previous DefaultDiff label provider when doing a non-directed comparison

JUnit to provide (TODO) : 
- test that opening an editor/ dialog in directed mode properly displays decorators
- same with undirected mode 
- test that updating the comparison (changing the direction) properly updates the decorators 

Git like decorators : 
![image](https://user-images.githubusercontent.com/109157813/202448516-57b1cf2c-6a3e-40ae-a7aa-98466f260b17.png)

Non-oriented decorators :
![image](https://user-images.githubusercontent.com/109157813/202448639-5f66663e-1755-4812-b813-eb9b9ba97567.png)
--------------------------------------------------------------------------------------------------------------------------------------------Documentation 

Ensures screenshots are up-to-date
Ensures doc is up-to-date

**Comment by hloehnert** [comment]
`IEditorInput editorInput = input.getEditorInput();` in line 2376 throws NPE in case input is null (e.g. switching to Text Compare)
